{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: "maoto-agent"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed -v

requirements:
  host:
    - python >=3.10,<3.12
    - setuptools >=74.1.1
    - wheel >=0.44.0
    - setuptools-scm >=8.1.0
  run:
    - python >=3.10,<3.12
    - aiohttp >=3.8.6
    - aiofiles >=22.1.0
    - requests >=2.32.3
    - gql >=3.4.0
    - websockets >=10.4
    - numpy >=1.26.4
    - setuptools >=74.1.1
    - psutil >=6.0.0
    - starlette >=0.37.2
    - python-dateutil >=2.9.0
    - psycopg2-binary >=2.9.9
    - uvicorn[standard] >=0.30.1
    - ariadne >=0.23.0
    - gunicorn >=22.0.0

about:
  home: https://maoto.world
  description: "Maoto Agent"
  license_file: LICENSE
  description: |
    Maoto Agent
  authors:
    - Maoto
  keywords:
    - "Maoto"
    - "Agent"
  classifiers:
    - "Programming Language :: Python :: 3"
    - "Operating System :: OS Independent"

extra:
  channels:
    - conda-forge
