package:
  name: "maoto-agent"
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}" 

source:
  path: .

build:
  noarch: python
  number: 0
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed -v

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools-scm
  run:
    - python >=3.10
    - websockets >=10.4
    - setuptools >=74.1.1
    - python-dateutil >=2.9.0
    - pydantic[email] >=2.10.6
    - email-validator >=2.2.0
    - fastapi >=0.115.12

about:
  home: https://maoto.world
  description: "Maoto Agent"
  license: Custom License
  license_file: LICENSE
  description: |
    Maoto Agent
  authors:
    - Maoto
  keywords:
    - "Maoto"
    - "Agent"
  classifiers:
    - "Programming Language :: Python :: 3"
    - "Operating System :: OS Independent"

extra:
  channels:
    - conda-forge
    - defaults
