{% set name = "maoto-agent" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - maoto-agent = maoto_agent.__main__:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=74.1.1
    - wheel >=0.44.0
    - setuptools-scm >=8.1.0
  run:
    - python >=3.10
    - gql >=3.4.0
    - websockets >=10.4
    - setuptools >=74.1.1
    - psutil >=6.0.0
    - python-dateutil >=2.9.0
    - aiohttp >=3.8.6
    - ariadne >=0.23.0
    - pydantic >=2.10.6
    - email-validator >=2.2.0

test:
  imports:
    - maoto_agent
  commands:
    - pip check
    - maoto-agent --help || true  # Allowing non-zero exit if it only prints help
  requires:
    - pip

about:
  home: https://maoto.world
  summary: Maoto Agent
  description: |
    Maoto Agent - Python package for interacting with Maoto services.
  license: Custom
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lennardkorte
