{% set name = "maoto-agent" %}

package:
  name: {{ name|lower }}
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  path: .

build:
  noarch: python
  number: 0
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed -v

requirements:
  host:
    - python
    - pip
    - hatchling
    - wheel
    - hatch-vcs
  run:
    - python >=3.10
    - pydantic >=2.9.2
    - pydantic-settings >=2.8.1
    - email-validator >=2.2.0
    - httpx >=0.28.1
    - fastapi >=0.115.12
    - loguru >=0.7.0
test:
  imports:
    - maoto_agent
  commands:
    - pip check
    - maoto-agent --help || true  # Allowing non-zero exit if it only prints help
  requires:
    - pip

about:
  home: https://maoto.world
  description: "Maoto Agent"
  license: LGPL-2.1-or-later
  license_file: LICENSE
  description: |
    Maoto Agent
  authors:
    - Maoto
  keywords:
    - "Maoto"
    - "Agent"
  classifiers:
    - "Programming Language :: Python :: 3"
    - "Operating System :: OS Independent"
    - "Intended Audience :: Information Technology"
    - "Intended Audience :: System Administrators"
    - "Topic :: Internet"
    - "Topic :: Software Development :: Libraries :: Application Frameworks"
    - "Topic :: Software Development :: Libraries :: Python Modules"
    - "Topic :: Software Development :: Libraries"
    - "Topic :: Software Development"
extra:
  channels:
    - conda-forge
    - defaults
