package:
  name: "maoto-agent"
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}" 

source:
  path: .

build:
  number: 0
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed -v

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools-scm
  run:
    - python
    - aiohttp
    - aiofiles
    - requests
    - gql
    - websockets
    - numpy
    - setuptools
    - psutil
    - starlette
    - python-dateutil
    - psycopg2-binary
    - uvicorn-standard
    - ariadne
    - gunicorn

about:
  home: https://maoto.world
  description: "Maoto Agent"
  license_file: LICENSE
  description: |
    Maoto Agent
  authors:
    - Maoto
  keywords:
    - "Maoto"
    - "Agent"
  classifiers:
    - "Programming Language :: Python :: 3"
    - "Operating System :: OS Independent"

extra:
  channels:
    - conda-forge
    - defaults
