{% set version = load_setup_py_data().get("version", "0.0.0") %}
{% set name = load_setup_py_data().get("name", "unknown") %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed -v

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=74.1.1
    - wheel >=0.44.0
    - setuptools-scm >=8.1.0
  run:
    - python >=3.10
    - aiohttp >=3.8.6
    - aiofiles >=22.1.0
    - requests >=2.32.3
    - gql >=3.4.0
    - websockets >=12.0
    - numpy >=1.26.4
    - setuptools >=74.1.1
    - psutil >=6.0.0

about:
  home: https://maoto.world
  summary: "Maoto Agent"
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Maoto Agent
  authors:
    - Maoto

build:
  channels:
    - conda-forge