name: Build and Publish Conda Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  prerelease_check:
    runs-on: ubuntu-latest
    outputs:
      is_prerelease: ${{ steps.prerelease.outputs.is_prerelease }}
    steps:
      - name: Determine if it's a pre-release
        id: prerelease
        run: |
          if [[ "${GITHUB_REF#refs/tags/}" =~ [a] ]]; then
            echo "is_prerelease=true" > $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" > $GITHUB_OUTPUT
          fi

  build_conda_package:
    needs: prerelease_check
    if: needs.prerelease_check.outputs.is_prerelease == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.10'

      - name: Install Conda build tools
        run: |
          conda install -y conda-build anaconda-client

      - name: Build Conda package
        run: |
          conda build .
      
      - name: Upload Conda build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: conda-packages
          path: /home/runner/miniconda3/conda-bld/***.tar.bz2

  deploy:
    needs: [prerelease_check, build_conda_package]
    if: needs.prerelease_check.outputs.is_prerelease == 'false'
    runs-on: ubuntu-latest
    environment: release_conda
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: conda-bld

      - name: Install Anaconda client
        run: |
          conda install -y anaconda-client

      - name: Publish to Conda or Test Channel
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          ls -l conda-bld
          if [[ "${GITHUB_REF#refs/tags/}" =~ [brc] ]]; then
            echo "Uploading to Test Conda Channel..."
            anaconda upload --label test conda-bld/***.tar.bz2 --token $ANACONDA_TOKEN
          else
            echo "Uploading to Production Conda Channel..."
            anaconda upload conda-bld/***.tar.bz2 --token $ANACONDA_TOKEN
