name: Build and Publish Conda Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  prerelease_check:
    runs-on: ubuntu-latest
    outputs:
      is_prerelease: ${{ steps.prerelease.outputs.is_prerelease }}
    steps:
      - name: Determine if it's a pre-release
        id: prerelease
        run: |
          if [[ "${GITHUB_REF#refs/tags/}" =~ [a] ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

  build_conda_package:
    needs: prerelease_check
    if: needs.prerelease_check.outputs.is_prerelease == 'false'
    runs-on: ubuntu-latest
    outputs:
      artifact_path: ${{ steps.build.outputs.artifact_path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.10'

      - name: Install Conda build tools
        run: |
          conda install -y conda-build anaconda-client

      - name: Build Conda package
        id: build
        run: |
          # Build the package and output the tar.bz2 file path
          artifact_path=$(conda build . -c conda-forge --output)
          echo "artifact_path=${artifact_path}" >> $GITHUB_OUTPUT

      - name: Upload Conda build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: conda-packages
          path: ${{ steps.build.outputs.artifact_path }}

  deploy:
    needs: [prerelease_check, build_conda_package]
    if: needs.prerelease_check.outputs.is_prerelease == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: conda-bld

      - name: Install Anaconda client
        run: |
          pip install anaconda-client

      - name: Publish to Conda or Test Channel
        run: |
          artifact=${{ needs.build_conda_package.outputs.artifact_path }}
          echo "Uploading artifact: $artifact"
          if [[ "${GITHUB_REF#refs/tags/}" =~ [brc] ]]; then
            echo "Uploading to Test Conda Channel..."
            anaconda upload --label beta $artifact
          else
            echo "Uploading to Production Conda Channel..."
            anaconda upload $artifact
          fi
