name: Build and Publish Pypi Package

on:
  push:
    tags:
      - 'v*'  # Runs when a version tag is pushed
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

 jobs:
   build-and-publish:
     runs-on: ubuntu-latest
     environment: release_pypi

     steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.10'

       - name: Install build and twine
         run: |
           python -m pip install --upgrade pip
           pip install build twine
       - name: Build the package
         run: python -m build

      #  - name: Publish to PyPI
      #    env:
      #      TWINE_USERNAME: __token__
      #      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      #    run: twine upload dist/*
