name: Test

on:
  push:
    branches:
      - main

jobs:
  changelog_job:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'CHANGELOG')
    steps:
      - name: Print message
        run: |
          echo "Triggered by CHANGELOG commit"