name: Versioner

on:
  workflow_dispatch:
    inputs:
      release_option:
        description: 'Select a version degree and release type'
        required: true
        type: choice         # <-- This is the new key!
        options:
          - Major Full
          - Major Beta
          - Minor Full
          - Minor Beta
          - Patch Full
          - Patch Beta
        default: 'Major Full'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Display selected release option
        run: |
            echo "Release option selected: ${{ github.event.inputs.release_option }}"
