name: Manual Release Workflow

on:
  workflow_dispatch:
    inputs:
      version_degree:
        description: 'Select a version degree'
        required: true
        default: 'Major'
        options:
          - 'Major'
          - 'Minor'
          - 'Patch'
      release_type:
        description: 'Select a release type'
        required: true
        default: 'Full'
        options:
          - 'Full'
          - 'Beta'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Display selected options
        run: |
          echo "Version degree selected: ${{ github.event.inputs.version_degree }}"
          echo "Release type selected: ${{ github.event.inputs.release_type }}"
